using UnityEngine;
using System.Collections;

public class GhostMoveAutoGenerated : MonoBehaviour {

	private Transform[] waypoints = new Transform[5];



		int wayPointsSize = 2;    
	int index = 0;

		
		public float speed = 0.3f;
		
		void FixedUpdate()
		{
		waypoints[0] = GameObject.Find("Waypoint00").transform;
		waypoints[1] = GameObject.Find("Waypoint01").transform;
		waypoints[2] = GameObject.Find("Waypoint02").transform;
		waypoints[3] = GameObject.Find("Waypoint01").transform;
		waypoints[4] = GameObject.Find("Waypoint00").transform;





			if  ((transform.position.x - waypoints[index].position.x > 0.01 || transform.position.x - waypoints[index].position.x <-0.01) ||
			     (transform.position.y - waypoints[index].position.y > 0.01 || transform.position.y - waypoints[index].position.y < -0.01))
				
			{
				Vector2 p = Vector2.MoveTowards(transform.position,
				                                waypoints[index].position,
				                                speed);
				GetComponent<Rigidbody2D>().MovePosition(p);
			}
			else index = (index + 1) % waypoints.Length;
			// Animation
			Vector2 dir = waypoints[index].position - transform.position;
			GetComponent<Animator>().SetFloat("DirX", dir.x);
			GetComponent<Animator>().SetFloat("DirY", dir.y);
		}
		void OnTriggerEnter2D(Collider2D co)
		{
			if (co.name == "pacman")
				Destroy(co.gameObject);
		}
	}
	
